import type { GiaoVien, PhanCong, DinhMuc, RangBuoc, LopHoc, TKBSlot, GvAccount } from "./types";

// ─── Tài khoản giáo viên ──────────────────────────────────────────────────────

export const GV_ACCOUNTS: GvAccount[] = [
  { ma_gv: "annv", ho_ten: "Nguyễn Văn An",      username: "nguyenan",   password: "123456", to_chuyen_mon: "Toán - Tin",  lop_chu_nhiem: "6/1" },
  { ma_gv: "binhtt", ho_ten: "Trần Thị Bình",      username: "tranbinh",   password: "123456", to_chuyen_mon: "Ngữ Văn",    lop_chu_nhiem: "6/2" },
  { ma_gv: "cuonglm", ho_ten: "Lê Minh Cường",      username: "lecuong",    password: "123456", to_chuyen_mon: "Ngoại Ngữ", lop_chu_nhiem: "6/3" },
  { ma_gv: "dungpt", ho_ten: "Phạm Thu Dung",      username: "phamdung",   password: "123456", to_chuyen_mon: "KHTN",       lop_chu_nhiem: "6/4" },
  { ma_gv: "emhv", ho_ten: "Hoàng Văn Em",       username: "hoangem",    password: "123456", to_chuyen_mon: "Sử - Địa",  lop_chu_nhiem: "6/5" },
  { ma_gv: "phuongvt", ho_ten: "Vũ Thị Phương",      username: "vuphuong",   password: "123456", to_chuyen_mon: "GDCD - TD", lop_chu_nhiem: "6/6" },
  { ma_gv: "giangdt", ho_ten: "Đặng Thị Giang",     username: "danggiang",  password: "123456", to_chuyen_mon: "Toán - Tin",  lop_chu_nhiem: "7/1" },
  { ma_gv: "hungnv", ho_ten: "Ngô Văn Hùng",       username: "ngohung",    password: "123456", to_chuyen_mon: "Ngữ Văn",    lop_chu_nhiem: "7/2" },
  { ma_gv: "lanbt", ho_ten: "Bùi Thị Lan",        username: "builan",     password: "123456", to_chuyen_mon: "Ngoại Ngữ", lop_chu_nhiem: "7/3" },
  { ma_gv: "minhtv", ho_ten: "Trịnh Văn Minh",     username: "trinhminh",  password: "123456", to_chuyen_mon: "KHTN",       lop_chu_nhiem: "7/4" },
  { ma_gv: "ngoclt", ho_ten: "Lý Thị Ngọc",        username: "lyngoc",     password: "123456", to_chuyen_mon: "Sử - Địa",  lop_chu_nhiem: "7/5" },
  { ma_gv: "onpv", ho_ten: "Phan Văn Ơn",        username: "phanon",     password: "123456", to_chuyen_mon: "Toán - Tin",  lop_chu_nhiem: "7/6" },
  { ma_gv: "phungmt", ho_ten: "Mai Thị Phụng",      username: "maiphung",   password: "123456", to_chuyen_mon: "Ngữ Văn",    lop_chu_nhiem: "8/1" },
  { ma_gv: "quyethv", ho_ten: "Hồ Văn Quyết",       username: "hoquyet",    password: "123456", to_chuyen_mon: "KHTN",       lop_chu_nhiem: "8/2" },
  { ma_gv: "rangdt", ho_ten: "Dương Thị Rạng",     username: "duongrang",  password: "123456", to_chuyen_mon: "Ngoại Ngữ", lop_chu_nhiem: "8/3" },
  { ma_gv: "soncv", ho_ten: "Cao Văn Sơn",        username: "caoson",     password: "123456", to_chuyen_mon: "Toán - Tin",  lop_chu_nhiem: "8/4" },
  { ma_gv: "tuyetdt", ho_ten: "Đinh Thị Tuyết",     username: "dinhttuyet", password: "123456", to_chuyen_mon: "Ngữ Văn",    lop_chu_nhiem: "8/5" },
  { ma_gv: "uylv", ho_ten: "Lưu Văn Uy",         username: "luuuy",      password: "123456", to_chuyen_mon: "GDCD - TD", lop_chu_nhiem: "8/6" },
  { ma_gv: "vantt", ho_ten: "Tống Thị Vân",       username: "tongvan",    password: "123456", to_chuyen_mon: "KHTN",       lop_chu_nhiem: "9/1" },
  { ma_gv: "xuankv", ho_ten: "Kiều Văn Xuân",      username: "kieuxuan",   password: "123456", to_chuyen_mon: "Toán - Tin",  lop_chu_nhiem: "9/2" },
  { ma_gv: "yenht", ho_ten: "Hà Thị Yến",         username: "hayen",      password: "123456", to_chuyen_mon: "Ngữ Văn",    lop_chu_nhiem: "9/3" },
  { ma_gv: "tungdv", ho_ten: "Đỗ Văn Tùng",        username: "dotung",     password: "123456", to_chuyen_mon: "Ngoại Ngữ", lop_chu_nhiem: "9/4" },
  { ma_gv: "anhnt", ho_ten: "Nguyễn Thị Ánh",     username: "nguyenanh",  password: "123456", to_chuyen_mon: "Sử - Địa",  lop_chu_nhiem: "9/5" },
  { ma_gv: "bactv", ho_ten: "Trần Văn Bắc",       username: "tranbac",    password: "123456", to_chuyen_mon: "GDCD - TD", lop_chu_nhiem: "9/6" },
];

// ─── Giáo viên ────────────────────────────────────────────────────────────────

export const MOCK_GIAO_VIEN: GiaoVien[] = [
  { id:  1, ma_gv: "annv", ho_ten: "Nguyễn Văn An",      to_chuyen_mon: "Toán - Tin",  chuc_vu: "Tổ trưởng", lop_chu_nhiem: "6/1", active: true, tong_tiet: 16 },
  { id:  2, ma_gv: "binhtt", ho_ten: "Trần Thị Bình",      to_chuyen_mon: "Ngữ Văn",    chuc_vu: null,        lop_chu_nhiem: "6/2", active: true, tong_tiet: 16 },
  { id:  3, ma_gv: "cuonglm", ho_ten: "Lê Minh Cường",      to_chuyen_mon: "Ngoại Ngữ", chuc_vu: null,        lop_chu_nhiem: "6/3", active: true, tong_tiet: 18 },
  { id:  4, ma_gv: "dungpt", ho_ten: "Phạm Thu Dung",      to_chuyen_mon: "KHTN",       chuc_vu: "Tổ phó",   lop_chu_nhiem: "6/4", active: true, tong_tiet: 24 },
  { id:  5, ma_gv: "emhv", ho_ten: "Hoàng Văn Em",       to_chuyen_mon: "Sử - Địa",  chuc_vu: null,        lop_chu_nhiem: "6/5", active: true, tong_tiet: 12 },
  { id:  6, ma_gv: "phuongvt", ho_ten: "Vũ Thị Phương",      to_chuyen_mon: "GDCD - TD", chuc_vu: null,        lop_chu_nhiem: "6/6", active: true, tong_tiet: 9  },
  { id:  7, ma_gv: "giangdt", ho_ten: "Đặng Thị Giang",     to_chuyen_mon: "Toán - Tin",  chuc_vu: null,        lop_chu_nhiem: "7/1", active: true, tong_tiet: 16 },
  { id:  8, ma_gv: "hungnv", ho_ten: "Ngô Văn Hùng",       to_chuyen_mon: "Ngữ Văn",    chuc_vu: null,        lop_chu_nhiem: "7/2", active: true, tong_tiet: 16 },
  { id:  9, ma_gv: "lanbt", ho_ten: "Bùi Thị Lan",        to_chuyen_mon: "Ngoại Ngữ", chuc_vu: null,        lop_chu_nhiem: "7/3", active: true, tong_tiet: 18 },
  { id: 10, ma_gv: "minhtv", ho_ten: "Trịnh Văn Minh",     to_chuyen_mon: "KHTN",       chuc_vu: "Tổ trưởng", lop_chu_nhiem: "7/4", active: true, tong_tiet: 24 },
  { id: 11, ma_gv: "ngoclt", ho_ten: "Lý Thị Ngọc",        to_chuyen_mon: "Sử - Địa",  chuc_vu: null,        lop_chu_nhiem: "7/5", active: true, tong_tiet: 12 },
  { id: 12, ma_gv: "onpv", ho_ten: "Phan Văn Ơn",        to_chuyen_mon: "Toán - Tin",  chuc_vu: null,        lop_chu_nhiem: "7/6", active: true, tong_tiet: 16 },
  { id: 13, ma_gv: "phungmt", ho_ten: "Mai Thị Phụng",      to_chuyen_mon: "Ngữ Văn",    chuc_vu: null,        lop_chu_nhiem: "8/1", active: true, tong_tiet: 16 },
  { id: 14, ma_gv: "quyethv", ho_ten: "Hồ Văn Quyết",       to_chuyen_mon: "KHTN",       chuc_vu: null,        lop_chu_nhiem: "8/2", active: true, tong_tiet: 16 },
  { id: 15, ma_gv: "rangdt", ho_ten: "Dương Thị Rạng",     to_chuyen_mon: "Ngoại Ngữ", chuc_vu: null,        lop_chu_nhiem: "8/3", active: true, tong_tiet: 18 },
  { id: 16, ma_gv: "soncv", ho_ten: "Cao Văn Sơn",        to_chuyen_mon: "Toán - Tin",  chuc_vu: "Tổ phó",   lop_chu_nhiem: "8/4", active: true, tong_tiet: 16 },
  { id: 17, ma_gv: "tuyetdt", ho_ten: "Đinh Thị Tuyết",     to_chuyen_mon: "Ngữ Văn",    chuc_vu: null,        lop_chu_nhiem: "8/5", active: true, tong_tiet: 16 },
  { id: 18, ma_gv: "uylv", ho_ten: "Lưu Văn Uy",         to_chuyen_mon: "GDCD - TD", chuc_vu: null,        lop_chu_nhiem: "8/6", active: true, tong_tiet: 9  },
  { id: 19, ma_gv: "vantt", ho_ten: "Tống Thị Vân",       to_chuyen_mon: "KHTN",       chuc_vu: null,        lop_chu_nhiem: "9/1", active: true, tong_tiet: 16 },
  { id: 20, ma_gv: "xuankv", ho_ten: "Kiều Văn Xuân",      to_chuyen_mon: "Toán - Tin",  chuc_vu: null,        lop_chu_nhiem: "9/2", active: true, tong_tiet: 16 },
  { id: 21, ma_gv: "yenht", ho_ten: "Hà Thị Yến",         to_chuyen_mon: "Ngữ Văn",    chuc_vu: "Tổ trưởng", lop_chu_nhiem: "9/3", active: true, tong_tiet: 16 },
  { id: 22, ma_gv: "tungdv", ho_ten: "Đỗ Văn Tùng",        to_chuyen_mon: "Ngoại Ngữ", chuc_vu: null,        lop_chu_nhiem: "9/4", active: true, tong_tiet: 18 },
  { id: 23, ma_gv: "anhnt", ho_ten: "Nguyễn Thị Ánh",     to_chuyen_mon: "Sử - Địa",  chuc_vu: "Tổ trưởng", lop_chu_nhiem: "9/5", active: true, tong_tiet: 12 },
  { id: 24, ma_gv: "bactv", ho_ten: "Trần Văn Bắc",       to_chuyen_mon: "GDCD - TD", chuc_vu: null,        lop_chu_nhiem: "9/6", active: true, tong_tiet: 9  },
];

// ─── Lớp học ──────────────────────────────────────────────────────────────────

export const MOCK_LOP_HOC: LopHoc[] = [
  // Khối 6
  { id:  1, ten_lop: "6/1", khoi: 6, gvcn: "annv" },
  { id:  2, ten_lop: "6/2", khoi: 6, gvcn: "binhtt" },
  { id:  3, ten_lop: "6/3", khoi: 6, gvcn: "cuonglm" },
  { id:  4, ten_lop: "6/4", khoi: 6, gvcn: "dungpt" },
  { id:  5, ten_lop: "6/5", khoi: 6, gvcn: "emhv" },
  { id:  6, ten_lop: "6/6", khoi: 6, gvcn: "phuongvt" },
  // Khối 7
  { id:  7, ten_lop: "7/1", khoi: 7, gvcn: "giangdt" },
  { id:  8, ten_lop: "7/2", khoi: 7, gvcn: "hungnv" },
  { id:  9, ten_lop: "7/3", khoi: 7, gvcn: "lanbt" },
  { id: 10, ten_lop: "7/4", khoi: 7, gvcn: "minhtv" },
  { id: 11, ten_lop: "7/5", khoi: 7, gvcn: "ngoclt" },
  { id: 12, ten_lop: "7/6", khoi: 7, gvcn: "onpv" },
  // Khối 8
  { id: 13, ten_lop: "8/1", khoi: 8, gvcn: "phungmt" },
  { id: 14, ten_lop: "8/2", khoi: 8, gvcn: "quyethv" },
  { id: 15, ten_lop: "8/3", khoi: 8, gvcn: "rangdt" },
  { id: 16, ten_lop: "8/4", khoi: 8, gvcn: "soncv" },
  { id: 17, ten_lop: "8/5", khoi: 8, gvcn: "tuyetdt" },
  { id: 18, ten_lop: "8/6", khoi: 8, gvcn: "uylv" },
  // Khối 9
  { id: 19, ten_lop: "9/1", khoi: 9, gvcn: "vantt" },
  { id: 20, ten_lop: "9/2", khoi: 9, gvcn: "xuankv" },
  { id: 21, ten_lop: "9/3", khoi: 9, gvcn: "yenht" },
  { id: 22, ten_lop: "9/4", khoi: 9, gvcn: "tungdv" },
  { id: 23, ten_lop: "9/5", khoi: 9, gvcn: "anhnt" },
  { id: 24, ten_lop: "9/6", khoi: 9, gvcn: "bactv" },
];

// ─── Phân công ────────────────────────────────────────────────────────────────

export const MOCK_PHAN_CONG: PhanCong[] = [
  // annv – Toán (khối 6, lớp 6/1–6/4)
  { id:   1, ma_gv: "annv", lop: "6/1", mon: "Toán", so_tiet_tuan: 4 },
  { id:   2, ma_gv: "annv", lop: "6/2", mon: "Toán", so_tiet_tuan: 4 },
  { id:   3, ma_gv: "annv", lop: "6/3", mon: "Toán", so_tiet_tuan: 4 },
  { id:   4, ma_gv: "annv", lop: "6/4", mon: "Toán", so_tiet_tuan: 4 },
  // binhtt – Ngữ Văn (6/1–6/4)
  { id:   5, ma_gv: "binhtt", lop: "6/1", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  { id:   6, ma_gv: "binhtt", lop: "6/2", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  { id:   7, ma_gv: "binhtt", lop: "6/3", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  { id:   8, ma_gv: "binhtt", lop: "6/4", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  // cuonglm – Tiếng Anh (toàn khối 6)
  { id:   9, ma_gv: "cuonglm", lop: "6/1", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id:  10, ma_gv: "cuonglm", lop: "6/2", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id:  11, ma_gv: "cuonglm", lop: "6/3", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id:  12, ma_gv: "cuonglm", lop: "6/4", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id:  13, ma_gv: "cuonglm", lop: "6/5", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id:  14, ma_gv: "cuonglm", lop: "6/6", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  // dungpt – KHTN (toàn khối 6)
  { id:  15, ma_gv: "dungpt", lop: "6/1", mon: "KHTN", so_tiet_tuan: 4 },
  { id:  16, ma_gv: "dungpt", lop: "6/2", mon: "KHTN", so_tiet_tuan: 4 },
  { id:  17, ma_gv: "dungpt", lop: "6/3", mon: "KHTN", so_tiet_tuan: 4 },
  { id:  18, ma_gv: "dungpt", lop: "6/4", mon: "KHTN", so_tiet_tuan: 4 },
  { id:  19, ma_gv: "dungpt", lop: "6/5", mon: "KHTN", so_tiet_tuan: 4 },
  { id:  20, ma_gv: "dungpt", lop: "6/6", mon: "KHTN", so_tiet_tuan: 4 },
  // emhv – Sử/Địa (toàn khối 6)
  { id:  21, ma_gv: "emhv", lop: "6/1", mon: "Lịch Sử", so_tiet_tuan: 2 },
  { id:  22, ma_gv: "emhv", lop: "6/2", mon: "Lịch Sử", so_tiet_tuan: 2 },
  { id:  23, ma_gv: "emhv", lop: "6/3", mon: "Địa Lý",  so_tiet_tuan: 2 },
  { id:  24, ma_gv: "emhv", lop: "6/4", mon: "Địa Lý",  so_tiet_tuan: 2 },
  { id:  25, ma_gv: "emhv", lop: "6/5", mon: "Lịch Sử", so_tiet_tuan: 2 },
  { id:  26, ma_gv: "emhv", lop: "6/6", mon: "Địa Lý",  so_tiet_tuan: 2 },
  // phuongvt – GDCD/TD (toàn khối 6)
  { id:  27, ma_gv: "phuongvt", lop: "6/1", mon: "GDCD",     so_tiet_tuan: 1 },
  { id:  28, ma_gv: "phuongvt", lop: "6/2", mon: "Thể dục",  so_tiet_tuan: 2 },
  { id:  29, ma_gv: "phuongvt", lop: "6/3", mon: "GDCD",     so_tiet_tuan: 1 },
  { id:  30, ma_gv: "phuongvt", lop: "6/4", mon: "Thể dục",  so_tiet_tuan: 2 },
  { id:  31, ma_gv: "phuongvt", lop: "6/5", mon: "GDCD",     so_tiet_tuan: 1 },
  { id:  32, ma_gv: "phuongvt", lop: "6/6", mon: "Thể dục",  so_tiet_tuan: 2 },
  // giangdt – Toán (6/5–6/6 + khối 7 lớp 7/1–7/2)
  { id:  33, ma_gv: "giangdt", lop: "6/5", mon: "Toán", so_tiet_tuan: 4 },
  { id:  34, ma_gv: "giangdt", lop: "6/6", mon: "Toán", so_tiet_tuan: 4 },
  { id:  35, ma_gv: "giangdt", lop: "7/1", mon: "Toán", so_tiet_tuan: 4 },
  { id:  36, ma_gv: "giangdt", lop: "7/2", mon: "Toán", so_tiet_tuan: 4 },
  // hungnv – Ngữ Văn (6/5–6/6 + 7/1–7/2)
  { id:  37, ma_gv: "hungnv", lop: "6/5", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  { id:  38, ma_gv: "hungnv", lop: "6/6", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  { id:  39, ma_gv: "hungnv", lop: "7/1", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  { id:  40, ma_gv: "hungnv", lop: "7/2", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  // lanbt – Tiếng Anh (toàn khối 7)
  { id:  41, ma_gv: "lanbt", lop: "7/1", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id:  42, ma_gv: "lanbt", lop: "7/2", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id:  43, ma_gv: "lanbt", lop: "7/3", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id:  44, ma_gv: "lanbt", lop: "7/4", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id:  45, ma_gv: "lanbt", lop: "7/5", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id:  46, ma_gv: "lanbt", lop: "7/6", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  // minhtv – KHTN (toàn khối 7)
  { id:  47, ma_gv: "minhtv", lop: "7/1", mon: "KHTN", so_tiet_tuan: 4 },
  { id:  48, ma_gv: "minhtv", lop: "7/2", mon: "KHTN", so_tiet_tuan: 4 },
  { id:  49, ma_gv: "minhtv", lop: "7/3", mon: "KHTN", so_tiet_tuan: 4 },
  { id:  50, ma_gv: "minhtv", lop: "7/4", mon: "KHTN", so_tiet_tuan: 4 },
  { id:  51, ma_gv: "minhtv", lop: "7/5", mon: "KHTN", so_tiet_tuan: 4 },
  { id:  52, ma_gv: "minhtv", lop: "7/6", mon: "KHTN", so_tiet_tuan: 4 },
  // ngoclt – Sử/Địa (toàn khối 7)
  { id:  53, ma_gv: "ngoclt", lop: "7/1", mon: "Lịch Sử", so_tiet_tuan: 2 },
  { id:  54, ma_gv: "ngoclt", lop: "7/2", mon: "Lịch Sử", so_tiet_tuan: 2 },
  { id:  55, ma_gv: "ngoclt", lop: "7/3", mon: "Địa Lý",  so_tiet_tuan: 2 },
  { id:  56, ma_gv: "ngoclt", lop: "7/4", mon: "Địa Lý",  so_tiet_tuan: 2 },
  { id:  57, ma_gv: "ngoclt", lop: "7/5", mon: "Lịch Sử", so_tiet_tuan: 2 },
  { id:  58, ma_gv: "ngoclt", lop: "7/6", mon: "Địa Lý",  so_tiet_tuan: 2 },
  // onpv – Toán (7/3–7/6)
  { id:  59, ma_gv: "onpv", lop: "7/3", mon: "Toán", so_tiet_tuan: 4 },
  { id:  60, ma_gv: "onpv", lop: "7/4", mon: "Toán", so_tiet_tuan: 4 },
  { id:  61, ma_gv: "onpv", lop: "7/5", mon: "Toán", so_tiet_tuan: 4 },
  { id:  62, ma_gv: "onpv", lop: "7/6", mon: "Toán", so_tiet_tuan: 4 },
  // phungmt – Ngữ Văn (7/3–7/4 + 8/1–8/2)
  { id:  63, ma_gv: "phungmt", lop: "7/3", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  { id:  64, ma_gv: "phungmt", lop: "7/4", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  { id:  65, ma_gv: "phungmt", lop: "8/1", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  { id:  66, ma_gv: "phungmt", lop: "8/2", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  // quyethv – KHTN (8/1–8/4)
  { id:  67, ma_gv: "quyethv", lop: "8/1", mon: "KHTN", so_tiet_tuan: 4 },
  { id:  68, ma_gv: "quyethv", lop: "8/2", mon: "KHTN", so_tiet_tuan: 4 },
  { id:  69, ma_gv: "quyethv", lop: "8/3", mon: "KHTN", so_tiet_tuan: 4 },
  { id:  70, ma_gv: "quyethv", lop: "8/4", mon: "KHTN", so_tiet_tuan: 4 },
  // rangdt – Tiếng Anh (toàn khối 8)
  { id:  71, ma_gv: "rangdt", lop: "8/1", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id:  72, ma_gv: "rangdt", lop: "8/2", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id:  73, ma_gv: "rangdt", lop: "8/3", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id:  74, ma_gv: "rangdt", lop: "8/4", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id:  75, ma_gv: "rangdt", lop: "8/5", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id:  76, ma_gv: "rangdt", lop: "8/6", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  // soncv – Toán (8/1–8/4)
  { id:  77, ma_gv: "soncv", lop: "8/1", mon: "Toán", so_tiet_tuan: 4 },
  { id:  78, ma_gv: "soncv", lop: "8/2", mon: "Toán", so_tiet_tuan: 4 },
  { id:  79, ma_gv: "soncv", lop: "8/3", mon: "Toán", so_tiet_tuan: 4 },
  { id:  80, ma_gv: "soncv", lop: "8/4", mon: "Toán", so_tiet_tuan: 4 },
  // tuyetdt – Ngữ Văn (7/5–7/6 + 8/3–8/4)
  { id:  81, ma_gv: "tuyetdt", lop: "7/5", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  { id:  82, ma_gv: "tuyetdt", lop: "7/6", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  { id:  83, ma_gv: "tuyetdt", lop: "8/3", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  { id:  84, ma_gv: "tuyetdt", lop: "8/4", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  // uylv – GDCD/TD (khối 7 + một số khối 8)
  { id:  85, ma_gv: "uylv", lop: "7/1", mon: "GDCD",    so_tiet_tuan: 1 },
  { id:  86, ma_gv: "uylv", lop: "7/2", mon: "Thể dục", so_tiet_tuan: 2 },
  { id:  87, ma_gv: "uylv", lop: "7/3", mon: "GDCD",    so_tiet_tuan: 1 },
  { id:  88, ma_gv: "uylv", lop: "8/1", mon: "Thể dục", so_tiet_tuan: 2 },
  { id:  89, ma_gv: "uylv", lop: "8/2", mon: "GDCD",    so_tiet_tuan: 1 },
  { id:  90, ma_gv: "uylv", lop: "8/3", mon: "Thể dục", so_tiet_tuan: 2 },
  // vantt – KHTN (8/5–8/6 + 9/1–9/2)
  { id:  91, ma_gv: "vantt", lop: "8/5", mon: "KHTN", so_tiet_tuan: 4 },
  { id:  92, ma_gv: "vantt", lop: "8/6", mon: "KHTN", so_tiet_tuan: 4 },
  { id:  93, ma_gv: "vantt", lop: "9/1", mon: "KHTN", so_tiet_tuan: 4 },
  { id:  94, ma_gv: "vantt", lop: "9/2", mon: "KHTN", so_tiet_tuan: 4 },
  // xuankv – Toán (8/5–8/6 + 9/1–9/2)
  { id:  95, ma_gv: "xuankv", lop: "8/5", mon: "Toán", so_tiet_tuan: 4 },
  { id:  96, ma_gv: "xuankv", lop: "8/6", mon: "Toán", so_tiet_tuan: 4 },
  { id:  97, ma_gv: "xuankv", lop: "9/1", mon: "Toán", so_tiet_tuan: 4 },
  { id:  98, ma_gv: "xuankv", lop: "9/2", mon: "Toán", so_tiet_tuan: 4 },
  // yenht – Ngữ Văn (8/5–8/6 + 9/1–9/2)
  { id:  99, ma_gv: "yenht", lop: "8/5", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  { id: 100, ma_gv: "yenht", lop: "8/6", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  { id: 101, ma_gv: "yenht", lop: "9/1", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  { id: 102, ma_gv: "yenht", lop: "9/2", mon: "Ngữ Văn", so_tiet_tuan: 4 },
  // tungdv – Tiếng Anh (toàn khối 9)
  { id: 103, ma_gv: "tungdv", lop: "9/1", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id: 104, ma_gv: "tungdv", lop: "9/2", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id: 105, ma_gv: "tungdv", lop: "9/3", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id: 106, ma_gv: "tungdv", lop: "9/4", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id: 107, ma_gv: "tungdv", lop: "9/5", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  { id: 108, ma_gv: "tungdv", lop: "9/6", mon: "Tiếng Anh", so_tiet_tuan: 3 },
  // anhnt – Sử/Địa (khối 8–9)
  { id: 109, ma_gv: "anhnt", lop: "8/1", mon: "Lịch Sử", so_tiet_tuan: 2 },
  { id: 110, ma_gv: "anhnt", lop: "8/2", mon: "Địa Lý",  so_tiet_tuan: 2 },
  { id: 111, ma_gv: "anhnt", lop: "9/1", mon: "Lịch Sử", so_tiet_tuan: 2 },
  { id: 112, ma_gv: "anhnt", lop: "9/2", mon: "Địa Lý",  so_tiet_tuan: 2 },
  { id: 113, ma_gv: "anhnt", lop: "9/3", mon: "Lịch Sử", so_tiet_tuan: 2 },
  { id: 114, ma_gv: "anhnt", lop: "9/4", mon: "Địa Lý",  so_tiet_tuan: 2 },
  // bactv – GDCD/TD (khối 8–9)
  { id: 115, ma_gv: "bactv", lop: "8/4", mon: "GDCD",    so_tiet_tuan: 1 },
  { id: 116, ma_gv: "bactv", lop: "8/5", mon: "Thể dục", so_tiet_tuan: 2 },
  { id: 117, ma_gv: "bactv", lop: "9/3", mon: "GDCD",    so_tiet_tuan: 1 },
  { id: 118, ma_gv: "bactv", lop: "9/4", mon: "Thể dục", so_tiet_tuan: 2 },
  { id: 119, ma_gv: "bactv", lop: "9/5", mon: "GDCD",    so_tiet_tuan: 1 },
  { id: 120, ma_gv: "bactv", lop: "9/6", mon: "Thể dục", so_tiet_tuan: 2 },
];

// ─── TKB (Thời khóa biểu) ─────────────────────────────────────────────────────
// thu: 2=Thứ Hai … 7=Thứ Bảy | buoi: sang/chieu | tiet: 1–5

export const MOCK_TKB: TKBSlot[] = [
  // ── annv – Toán (6/1–6/4) ──────────────────────────────────────────────────
  { id:   1, thu: 2, buoi: "sang",  tiet: 1, ma_gv: "annv", lop: "6/1", mon: "Toán" },
  { id:   2, thu: 2, buoi: "sang",  tiet: 2, ma_gv: "annv", lop: "6/2", mon: "Toán" },
  { id:   3, thu: 3, buoi: "sang",  tiet: 1, ma_gv: "annv", lop: "6/3", mon: "Toán" },
  { id:   4, thu: 3, buoi: "sang",  tiet: 2, ma_gv: "annv", lop: "6/4", mon: "Toán" },
  { id:   5, thu: 4, buoi: "sang",  tiet: 1, ma_gv: "annv", lop: "6/1", mon: "Toán" },
  { id:   6, thu: 5, buoi: "sang",  tiet: 2, ma_gv: "annv", lop: "6/2", mon: "Toán" },
  // ── binhtt – Ngữ Văn (6/1–6/4) ──────────────────────────────────────────────
  { id:   7, thu: 2, buoi: "sang",  tiet: 3, ma_gv: "binhtt", lop: "6/1", mon: "Ngữ Văn" },
  { id:   8, thu: 2, buoi: "sang",  tiet: 4, ma_gv: "binhtt", lop: "6/2", mon: "Ngữ Văn" },
  { id:   9, thu: 3, buoi: "sang",  tiet: 3, ma_gv: "binhtt", lop: "6/3", mon: "Ngữ Văn" },
  { id:  10, thu: 4, buoi: "sang",  tiet: 3, ma_gv: "binhtt", lop: "6/1", mon: "Ngữ Văn" },
  { id:  11, thu: 5, buoi: "sang",  tiet: 3, ma_gv: "binhtt", lop: "6/2", mon: "Ngữ Văn" },
  { id:  12, thu: 6, buoi: "sang",  tiet: 1, ma_gv: "binhtt", lop: "6/4", mon: "Ngữ Văn" },
  // ── cuonglm – Tiếng Anh (6/1–6/6) ────────────────────────────────────────────
  { id:  13, thu: 2, buoi: "chieu", tiet: 1, ma_gv: "cuonglm", lop: "6/1", mon: "Tiếng Anh" },
  { id:  14, thu: 2, buoi: "chieu", tiet: 2, ma_gv: "cuonglm", lop: "6/2", mon: "Tiếng Anh" },
  { id:  15, thu: 3, buoi: "chieu", tiet: 1, ma_gv: "cuonglm", lop: "6/3", mon: "Tiếng Anh" },
  { id:  16, thu: 4, buoi: "chieu", tiet: 1, ma_gv: "cuonglm", lop: "6/4", mon: "Tiếng Anh" },
  { id:  17, thu: 5, buoi: "chieu", tiet: 1, ma_gv: "cuonglm", lop: "6/5", mon: "Tiếng Anh" },
  { id:  18, thu: 6, buoi: "chieu", tiet: 1, ma_gv: "cuonglm", lop: "6/6", mon: "Tiếng Anh" },
  // ── dungpt – KHTN (6/1–6/6) ──────────────────────────────────────────────────
  { id:  19, thu: 2, buoi: "chieu", tiet: 3, ma_gv: "dungpt", lop: "6/1", mon: "KHTN" },
  { id:  20, thu: 2, buoi: "chieu", tiet: 4, ma_gv: "dungpt", lop: "6/2", mon: "KHTN" },
  { id:  21, thu: 3, buoi: "chieu", tiet: 3, ma_gv: "dungpt", lop: "6/3", mon: "KHTN" },
  { id:  22, thu: 4, buoi: "chieu", tiet: 3, ma_gv: "dungpt", lop: "6/4", mon: "KHTN" },
  { id:  23, thu: 5, buoi: "chieu", tiet: 3, ma_gv: "dungpt", lop: "6/5", mon: "KHTN" },
  { id:  24, thu: 6, buoi: "chieu", tiet: 3, ma_gv: "dungpt", lop: "6/6", mon: "KHTN" },
  // ── emhv – Lịch Sử/Địa Lý (6/1–6/6) ──────────────────────────────────────
  { id:  25, thu: 3, buoi: "sang",  tiet: 4, ma_gv: "emhv", lop: "6/1", mon: "Lịch Sử" },
  { id:  26, thu: 3, buoi: "sang",  tiet: 5, ma_gv: "emhv", lop: "6/2", mon: "Lịch Sử" },
  { id:  27, thu: 4, buoi: "sang",  tiet: 4, ma_gv: "emhv", lop: "6/3", mon: "Địa Lý"  },
  { id:  28, thu: 4, buoi: "sang",  tiet: 5, ma_gv: "emhv", lop: "6/4", mon: "Địa Lý"  },
  { id:  29, thu: 5, buoi: "sang",  tiet: 4, ma_gv: "emhv", lop: "6/5", mon: "Lịch Sử" },
  { id:  30, thu: 5, buoi: "sang",  tiet: 5, ma_gv: "emhv", lop: "6/6", mon: "Địa Lý"  },
  // ── phuongvt – GDCD/Thể dục (6/1–6/6) ─────────────────────────────────────────
  { id:  31, thu: 2, buoi: "sang",  tiet: 5, ma_gv: "phuongvt", lop: "6/1", mon: "GDCD"     },
  { id:  32, thu: 3, buoi: "chieu", tiet: 4, ma_gv: "phuongvt", lop: "6/2", mon: "Thể dục"  },
  { id:  33, thu: 4, buoi: "chieu", tiet: 4, ma_gv: "phuongvt", lop: "6/3", mon: "GDCD"     },
  { id:  34, thu: 5, buoi: "chieu", tiet: 4, ma_gv: "phuongvt", lop: "6/4", mon: "Thể dục"  },
  { id:  35, thu: 6, buoi: "sang",  tiet: 3, ma_gv: "phuongvt", lop: "6/5", mon: "GDCD"     },
  { id:  36, thu: 6, buoi: "chieu", tiet: 2, ma_gv: "phuongvt", lop: "6/6", mon: "Thể dục"  },
  // ── giangdt – Toán (6/5–6/6, 7/1–7/2) ────────────────────────────────────────
  { id:  37, thu: 2, buoi: "sang",  tiet: 1, ma_gv: "giangdt", lop: "6/5", mon: "Toán" },
  { id:  38, thu: 2, buoi: "sang",  tiet: 2, ma_gv: "giangdt", lop: "6/6", mon: "Toán" },
  { id:  39, thu: 3, buoi: "sang",  tiet: 1, ma_gv: "giangdt", lop: "7/1", mon: "Toán" },
  { id:  40, thu: 3, buoi: "sang",  tiet: 2, ma_gv: "giangdt", lop: "7/2", mon: "Toán" },
  { id:  41, thu: 4, buoi: "sang",  tiet: 2, ma_gv: "giangdt", lop: "6/5", mon: "Toán" },
  { id:  42, thu: 5, buoi: "sang",  tiet: 1, ma_gv: "giangdt", lop: "7/1", mon: "Toán" },
  // ── hungnv – Ngữ Văn (6/5–6/6, 7/1–7/2) ─────────────────────────────────────
  { id:  43, thu: 2, buoi: "sang",  tiet: 3, ma_gv: "hungnv", lop: "6/5", mon: "Ngữ Văn" },
  { id:  44, thu: 2, buoi: "sang",  tiet: 4, ma_gv: "hungnv", lop: "6/6", mon: "Ngữ Văn" },
  { id:  45, thu: 3, buoi: "sang",  tiet: 3, ma_gv: "hungnv", lop: "7/1", mon: "Ngữ Văn" },
  { id:  46, thu: 3, buoi: "sang",  tiet: 4, ma_gv: "hungnv", lop: "7/2", mon: "Ngữ Văn" },
  { id:  47, thu: 4, buoi: "sang",  tiet: 3, ma_gv: "hungnv", lop: "6/5", mon: "Ngữ Văn" },
  { id:  48, thu: 6, buoi: "sang",  tiet: 1, ma_gv: "hungnv", lop: "7/2", mon: "Ngữ Văn" },
  // ── lanbt – Tiếng Anh (7/1–7/6) ────────────────────────────────────────────
  { id:  49, thu: 2, buoi: "chieu", tiet: 1, ma_gv: "lanbt", lop: "7/1", mon: "Tiếng Anh" },
  { id:  50, thu: 2, buoi: "chieu", tiet: 2, ma_gv: "lanbt", lop: "7/2", mon: "Tiếng Anh" },
  { id:  51, thu: 3, buoi: "chieu", tiet: 1, ma_gv: "lanbt", lop: "7/3", mon: "Tiếng Anh" },
  { id:  52, thu: 4, buoi: "chieu", tiet: 1, ma_gv: "lanbt", lop: "7/4", mon: "Tiếng Anh" },
  { id:  53, thu: 5, buoi: "chieu", tiet: 1, ma_gv: "lanbt", lop: "7/5", mon: "Tiếng Anh" },
  { id:  54, thu: 6, buoi: "chieu", tiet: 1, ma_gv: "lanbt", lop: "7/6", mon: "Tiếng Anh" },
  // ── minhtv – KHTN (7/1–7/6) ──────────────────────────────────────────────────
  { id:  55, thu: 2, buoi: "chieu", tiet: 3, ma_gv: "minhtv", lop: "7/1", mon: "KHTN" },
  { id:  56, thu: 2, buoi: "chieu", tiet: 4, ma_gv: "minhtv", lop: "7/2", mon: "KHTN" },
  { id:  57, thu: 3, buoi: "chieu", tiet: 3, ma_gv: "minhtv", lop: "7/3", mon: "KHTN" },
  { id:  58, thu: 4, buoi: "chieu", tiet: 3, ma_gv: "minhtv", lop: "7/4", mon: "KHTN" },
  { id:  59, thu: 5, buoi: "chieu", tiet: 3, ma_gv: "minhtv", lop: "7/5", mon: "KHTN" },
  { id:  60, thu: 6, buoi: "chieu", tiet: 3, ma_gv: "minhtv", lop: "7/6", mon: "KHTN" },
  // ── ngoclt – Lịch Sử/Địa Lý (7/1–7/6) ──────────────────────────────────────
  { id:  61, thu: 3, buoi: "sang",  tiet: 4, ma_gv: "ngoclt", lop: "7/1", mon: "Lịch Sử" },
  { id:  62, thu: 3, buoi: "sang",  tiet: 5, ma_gv: "ngoclt", lop: "7/2", mon: "Lịch Sử" },
  { id:  63, thu: 4, buoi: "sang",  tiet: 4, ma_gv: "ngoclt", lop: "7/3", mon: "Địa Lý"  },
  { id:  64, thu: 4, buoi: "sang",  tiet: 5, ma_gv: "ngoclt", lop: "7/4", mon: "Địa Lý"  },
  { id:  65, thu: 5, buoi: "sang",  tiet: 4, ma_gv: "ngoclt", lop: "7/5", mon: "Lịch Sử" },
  { id:  66, thu: 5, buoi: "sang",  tiet: 5, ma_gv: "ngoclt", lop: "7/6", mon: "Địa Lý"  },
  // ── onpv – Toán (7/3–7/6) ──────────────────────────────────────────────────
  { id:  67, thu: 2, buoi: "sang",  tiet: 1, ma_gv: "onpv", lop: "7/3", mon: "Toán" },
  { id:  68, thu: 2, buoi: "sang",  tiet: 2, ma_gv: "onpv", lop: "7/4", mon: "Toán" },
  { id:  69, thu: 3, buoi: "sang",  tiet: 1, ma_gv: "onpv", lop: "7/5", mon: "Toán" },
  { id:  70, thu: 3, buoi: "sang",  tiet: 2, ma_gv: "onpv", lop: "7/6", mon: "Toán" },
  { id:  71, thu: 4, buoi: "sang",  tiet: 1, ma_gv: "onpv", lop: "7/3", mon: "Toán" },
  { id:  72, thu: 5, buoi: "sang",  tiet: 1, ma_gv: "onpv", lop: "7/5", mon: "Toán" },
  // ── phungmt – Ngữ Văn (7/3–7/4, 8/1–8/2) ─────────────────────────────────────
  { id:  73, thu: 2, buoi: "sang",  tiet: 3, ma_gv: "phungmt", lop: "7/3", mon: "Ngữ Văn" },
  { id:  74, thu: 2, buoi: "sang",  tiet: 4, ma_gv: "phungmt", lop: "7/4", mon: "Ngữ Văn" },
  { id:  75, thu: 3, buoi: "sang",  tiet: 3, ma_gv: "phungmt", lop: "8/1", mon: "Ngữ Văn" },
  { id:  76, thu: 3, buoi: "sang",  tiet: 4, ma_gv: "phungmt", lop: "8/2", mon: "Ngữ Văn" },
  { id:  77, thu: 4, buoi: "sang",  tiet: 3, ma_gv: "phungmt", lop: "7/3", mon: "Ngữ Văn" },
  { id:  78, thu: 6, buoi: "sang",  tiet: 2, ma_gv: "phungmt", lop: "8/1", mon: "Ngữ Văn" },
  // ── quyethv – KHTN (8/1–8/4) ──────────────────────────────────────────────────
  { id:  79, thu: 2, buoi: "chieu", tiet: 1, ma_gv: "quyethv", lop: "8/1", mon: "KHTN" },
  { id:  80, thu: 2, buoi: "chieu", tiet: 2, ma_gv: "quyethv", lop: "8/2", mon: "KHTN" },
  { id:  81, thu: 3, buoi: "chieu", tiet: 1, ma_gv: "quyethv", lop: "8/3", mon: "KHTN" },
  { id:  82, thu: 3, buoi: "chieu", tiet: 2, ma_gv: "quyethv", lop: "8/4", mon: "KHTN" },
  { id:  83, thu: 4, buoi: "chieu", tiet: 1, ma_gv: "quyethv", lop: "8/1", mon: "KHTN" },
  { id:  84, thu: 5, buoi: "chieu", tiet: 1, ma_gv: "quyethv", lop: "8/2", mon: "KHTN" },
  // ── rangdt – Tiếng Anh (8/1–8/6) ────────────────────────────────────────────
  { id:  85, thu: 2, buoi: "chieu", tiet: 3, ma_gv: "rangdt", lop: "8/1", mon: "Tiếng Anh" },
  { id:  86, thu: 2, buoi: "chieu", tiet: 4, ma_gv: "rangdt", lop: "8/2", mon: "Tiếng Anh" },
  { id:  87, thu: 3, buoi: "chieu", tiet: 3, ma_gv: "rangdt", lop: "8/3", mon: "Tiếng Anh" },
  { id:  88, thu: 4, buoi: "chieu", tiet: 3, ma_gv: "rangdt", lop: "8/4", mon: "Tiếng Anh" },
  { id:  89, thu: 5, buoi: "chieu", tiet: 3, ma_gv: "rangdt", lop: "8/5", mon: "Tiếng Anh" },
  { id:  90, thu: 6, buoi: "chieu", tiet: 3, ma_gv: "rangdt", lop: "8/6", mon: "Tiếng Anh" },
  // ── soncv – Toán (8/1–8/4) ──────────────────────────────────────────────────
  { id:  91, thu: 2, buoi: "sang",  tiet: 1, ma_gv: "soncv", lop: "8/1", mon: "Toán" },
  { id:  92, thu: 2, buoi: "sang",  tiet: 2, ma_gv: "soncv", lop: "8/2", mon: "Toán" },
  { id:  93, thu: 3, buoi: "sang",  tiet: 1, ma_gv: "soncv", lop: "8/3", mon: "Toán" },
  { id:  94, thu: 3, buoi: "sang",  tiet: 2, ma_gv: "soncv", lop: "8/4", mon: "Toán" },
  { id:  95, thu: 4, buoi: "sang",  tiet: 2, ma_gv: "soncv", lop: "8/1", mon: "Toán" },
  { id:  96, thu: 5, buoi: "sang",  tiet: 2, ma_gv: "soncv", lop: "8/2", mon: "Toán" },
  // ── tuyetdt – Ngữ Văn (7/5–7/6, 8/3–8/4) ─────────────────────────────────────
  { id:  97, thu: 2, buoi: "sang",  tiet: 3, ma_gv: "tuyetdt", lop: "7/5", mon: "Ngữ Văn" },
  { id:  98, thu: 2, buoi: "sang",  tiet: 4, ma_gv: "tuyetdt", lop: "7/6", mon: "Ngữ Văn" },
  { id:  99, thu: 3, buoi: "sang",  tiet: 3, ma_gv: "tuyetdt", lop: "8/3", mon: "Ngữ Văn" },
  { id: 100, thu: 3, buoi: "sang",  tiet: 4, ma_gv: "tuyetdt", lop: "8/4", mon: "Ngữ Văn" },
  { id: 101, thu: 4, buoi: "sang",  tiet: 4, ma_gv: "tuyetdt", lop: "7/5", mon: "Ngữ Văn" },
  { id: 102, thu: 6, buoi: "sang",  tiet: 3, ma_gv: "tuyetdt", lop: "8/3", mon: "Ngữ Văn" },
  // ── uylv – GDCD/Thể dục (7/1–7/3, 8/1–8/3) ────────────────────────────────
  { id: 103, thu: 3, buoi: "chieu", tiet: 4, ma_gv: "uylv", lop: "7/1", mon: "GDCD"    },
  { id: 104, thu: 4, buoi: "chieu", tiet: 4, ma_gv: "uylv", lop: "7/2", mon: "Thể dục" },
  { id: 105, thu: 5, buoi: "chieu", tiet: 4, ma_gv: "uylv", lop: "8/1", mon: "Thể dục" },
  { id: 106, thu: 5, buoi: "chieu", tiet: 5, ma_gv: "uylv", lop: "8/2", mon: "GDCD"    },
  { id: 107, thu: 6, buoi: "sang",  tiet: 4, ma_gv: "uylv", lop: "7/3", mon: "GDCD"    },
  { id: 108, thu: 6, buoi: "chieu", tiet: 4, ma_gv: "uylv", lop: "8/3", mon: "Thể dục" },
  // ── vantt – KHTN (8/5–8/6, 9/1–9/2) ────────────────────────────────────────
  { id: 109, thu: 2, buoi: "chieu", tiet: 1, ma_gv: "vantt", lop: "8/5", mon: "KHTN" },
  { id: 110, thu: 2, buoi: "chieu", tiet: 2, ma_gv: "vantt", lop: "8/6", mon: "KHTN" },
  { id: 111, thu: 3, buoi: "chieu", tiet: 1, ma_gv: "vantt", lop: "9/1", mon: "KHTN" },
  { id: 112, thu: 3, buoi: "chieu", tiet: 2, ma_gv: "vantt", lop: "9/2", mon: "KHTN" },
  { id: 113, thu: 4, buoi: "chieu", tiet: 2, ma_gv: "vantt", lop: "8/5", mon: "KHTN" },
  { id: 114, thu: 5, buoi: "chieu", tiet: 2, ma_gv: "vantt", lop: "9/1", mon: "KHTN" },
  // ── xuankv – Toán (8/5–8/6, 9/1–9/2) ────────────────────────────────────────
  { id: 115, thu: 2, buoi: "sang",  tiet: 1, ma_gv: "xuankv", lop: "8/5", mon: "Toán" },
  { id: 116, thu: 2, buoi: "sang",  tiet: 2, ma_gv: "xuankv", lop: "8/6", mon: "Toán" },
  { id: 117, thu: 3, buoi: "sang",  tiet: 1, ma_gv: "xuankv", lop: "9/1", mon: "Toán" },
  { id: 118, thu: 3, buoi: "sang",  tiet: 2, ma_gv: "xuankv", lop: "9/2", mon: "Toán" },
  { id: 119, thu: 4, buoi: "sang",  tiet: 3, ma_gv: "xuankv", lop: "8/5", mon: "Toán" },
  { id: 120, thu: 5, buoi: "sang",  tiet: 3, ma_gv: "xuankv", lop: "9/1", mon: "Toán" },
  // ── yenht – Ngữ Văn (8/5–8/6, 9/1–9/2) ─────────────────────────────────────
  { id: 121, thu: 2, buoi: "sang",  tiet: 3, ma_gv: "yenht", lop: "8/5", mon: "Ngữ Văn" },
  { id: 122, thu: 2, buoi: "sang",  tiet: 4, ma_gv: "yenht", lop: "8/6", mon: "Ngữ Văn" },
  { id: 123, thu: 3, buoi: "sang",  tiet: 3, ma_gv: "yenht", lop: "9/1", mon: "Ngữ Văn" },
  { id: 124, thu: 3, buoi: "sang",  tiet: 4, ma_gv: "yenht", lop: "9/2", mon: "Ngữ Văn" },
  { id: 125, thu: 4, buoi: "sang",  tiet: 4, ma_gv: "yenht", lop: "8/5", mon: "Ngữ Văn" },
  { id: 126, thu: 6, buoi: "sang",  tiet: 1, ma_gv: "yenht", lop: "9/2", mon: "Ngữ Văn" },
  // ── tungdv – Tiếng Anh (9/1–9/6) ────────────────────────────────────────────
  { id: 127, thu: 2, buoi: "chieu", tiet: 3, ma_gv: "tungdv", lop: "9/1", mon: "Tiếng Anh" },
  { id: 128, thu: 2, buoi: "chieu", tiet: 4, ma_gv: "tungdv", lop: "9/2", mon: "Tiếng Anh" },
  { id: 129, thu: 3, buoi: "chieu", tiet: 3, ma_gv: "tungdv", lop: "9/3", mon: "Tiếng Anh" },
  { id: 130, thu: 4, buoi: "chieu", tiet: 3, ma_gv: "tungdv", lop: "9/4", mon: "Tiếng Anh" },
  { id: 131, thu: 5, buoi: "chieu", tiet: 3, ma_gv: "tungdv", lop: "9/5", mon: "Tiếng Anh" },
  { id: 132, thu: 6, buoi: "chieu", tiet: 3, ma_gv: "tungdv", lop: "9/6", mon: "Tiếng Anh" },
  // ── anhnt – Lịch Sử/Địa Lý (8/1–9/4) ──────────────────────────────────────
  { id: 133, thu: 3, buoi: "sang",  tiet: 4, ma_gv: "anhnt", lop: "8/1", mon: "Lịch Sử" },
  { id: 134, thu: 3, buoi: "sang",  tiet: 5, ma_gv: "anhnt", lop: "8/2", mon: "Địa Lý"  },
  { id: 135, thu: 4, buoi: "sang",  tiet: 4, ma_gv: "anhnt", lop: "8/3", mon: "Lịch Sử" },
  { id: 136, thu: 4, buoi: "sang",  tiet: 5, ma_gv: "anhnt", lop: "9/1", mon: "Địa Lý"  },
  { id: 137, thu: 5, buoi: "sang",  tiet: 4, ma_gv: "anhnt", lop: "9/2", mon: "Lịch Sử" },
  { id: 138, thu: 5, buoi: "sang",  tiet: 5, ma_gv: "anhnt", lop: "9/3", mon: "Địa Lý"  },
  // ── bactv – GDCD/Thể dục (8/4–9/6) ─────────────────────────────────────────
  { id: 139, thu: 3, buoi: "chieu", tiet: 4, ma_gv: "bactv", lop: "8/4", mon: "GDCD"    },
  { id: 140, thu: 4, buoi: "chieu", tiet: 4, ma_gv: "bactv", lop: "8/5", mon: "Thể dục" },
  { id: 141, thu: 5, buoi: "chieu", tiet: 4, ma_gv: "bactv", lop: "8/6", mon: "GDCD"    },
  { id: 142, thu: 5, buoi: "chieu", tiet: 5, ma_gv: "bactv", lop: "9/4", mon: "Thể dục" },
  { id: 143, thu: 6, buoi: "sang",  tiet: 4, ma_gv: "bactv", lop: "9/5", mon: "GDCD"    },
  { id: 144, thu: 6, buoi: "chieu", tiet: 4, ma_gv: "bactv", lop: "9/6", mon: "Thể dục" },
];

// ─── Định mức ─────────────────────────────────────────────────────────────────

export const MOCK_DINH_MUC: DinhMuc[] = [
  { id:  1, khoi: "6", mon: "Toán",       so_tiet_tuan: 4, gioi_han_buoi: 2 },
  { id:  2, khoi: "6", mon: "Ngữ Văn",   so_tiet_tuan: 4, gioi_han_buoi: 2 },
  { id:  3, khoi: "6", mon: "Tiếng Anh", so_tiet_tuan: 3, gioi_han_buoi: 2 },
  { id:  4, khoi: "6", mon: "KHTN",      so_tiet_tuan: 4, gioi_han_buoi: 2 },
  { id:  5, khoi: "6", mon: "Lịch Sử",  so_tiet_tuan: 2, gioi_han_buoi: 1 },
  { id:  6, khoi: "6", mon: "Địa Lý",   so_tiet_tuan: 2, gioi_han_buoi: 1 },
  { id:  7, khoi: "6", mon: "GDCD",      so_tiet_tuan: 1, gioi_han_buoi: 1 },
  { id:  8, khoi: "6", mon: "Thể dục",  so_tiet_tuan: 2, gioi_han_buoi: 1 },
  { id:  9, khoi: "7", mon: "Toán",       so_tiet_tuan: 4, gioi_han_buoi: 2 },
  { id: 10, khoi: "7", mon: "Ngữ Văn",   so_tiet_tuan: 4, gioi_han_buoi: 2 },
  { id: 11, khoi: "7", mon: "Tiếng Anh", so_tiet_tuan: 3, gioi_han_buoi: 2 },
  { id: 12, khoi: "7", mon: "KHTN",      so_tiet_tuan: 4, gioi_han_buoi: 2 },
  { id: 13, khoi: "7", mon: "Lịch Sử",  so_tiet_tuan: 2, gioi_han_buoi: 1 },
  { id: 14, khoi: "7", mon: "Địa Lý",   so_tiet_tuan: 2, gioi_han_buoi: 1 },
  { id: 15, khoi: "8", mon: "Toán",       so_tiet_tuan: 4, gioi_han_buoi: 2 },
  { id: 16, khoi: "8", mon: "Ngữ Văn",   so_tiet_tuan: 4, gioi_han_buoi: 2 },
  { id: 17, khoi: "8", mon: "Tiếng Anh", so_tiet_tuan: 3, gioi_han_buoi: 2 },
  { id: 18, khoi: "8", mon: "KHTN",      so_tiet_tuan: 4, gioi_han_buoi: 2 },
  { id: 19, khoi: "9", mon: "Toán",       so_tiet_tuan: 4, gioi_han_buoi: 2 },
  { id: 20, khoi: "9", mon: "Ngữ Văn",   so_tiet_tuan: 4, gioi_han_buoi: 2 },
  { id: 21, khoi: "9", mon: "Tiếng Anh", so_tiet_tuan: 4, gioi_han_buoi: 2 },
  { id: 22, khoi: "9", mon: "KHTN",      so_tiet_tuan: 4, gioi_han_buoi: 2 },
];

// ─── Ràng buộc ────────────────────────────────────────────────────────────────

export const MOCK_RANG_BUOC: RangBuoc[] = [
  { id: 1, rule_code: "NO_CONSECUTIVE_5", mo_ta: "Giáo viên không dạy 5 tiết liên tiếp",         loai: "hard", active: true, is_template: true, editable_params: [] },
  { id: 2, rule_code: "MAX_2_PER_DAY",    mo_ta: "Tối đa 2 tiết/ngày/môn cho 1 lớp",             loai: "hard", active: true, is_template: true, editable_params: [] },
  { id: 3, rule_code: "NO_SPLIT_SESSION", mo_ta: "Không tách buổi với môn chỉ 1 tiết/tuần",      loai: "soft", active: true, is_template: true, editable_params: [] },
  { id: 4, rule_code: "BALANCE_WEEK",     mo_ta: "Phân phối đều tiết trong tuần",                 loai: "soft", active: true, is_template: true, editable_params: [] },
  { id: 5, rule_code: "GVCN_MONDAY",      mo_ta: "GVCN có tiết đầu thứ Hai (chào cờ)",           loai: "hard", active: true, is_template: true, editable_params: [] },
];
